name: launch
on:
  workflow_dispatch:
    inputs:
      aws_region:
        default: 'eu-central-1'
        required: true
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout emc
        uses: actions/checkout@v2
        with:
          path: emc

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.aws_region }}

      - name: Add ops
        working-directory: emc
        run: sed -i 's/OPS=/OPS=${{ secrets.MINECRAFT_OPS }}/' mc.yaml

      - name: Add motd
        working-directory: emc
        run: sed 's/MOTD=/MOTD=${{ secrets.MINECRAFT_MOTD }}/' mc.yaml

      - name: Add icon
        working-directory: emc
        run: sed 's/ICON=/ICON=${{ secrets.MINECRAFT_ICON }}/' mc.yaml

      - name: Launch server
        working-directory: emc
        run: make state/ec2_ip

      - name: Notify Quint
        working-directory: emc
        run: curl -sX POST "https://push.guvernator.net/message?token=${{ secrets.GOTIFY_TOKEN }}" -F "title=emc" -F "priority=8" -F "message=new server at $(cat state/ec2_ip)"

      - name: Upload key
        working-directory: emc
        run: curl -su "${{ secrets.NEXTCLOUD_USER }}:${{ secrets.NEXTCLOUD_PASSWORD }}" -T state/minecraft.pem "https://${{ secrets.NEXTCLOUD_URL }}/remote.php/dav/files/${{ secrets.NEXTCLOUD_USER }}/Minecraft/$(date -I | tr -d -)-$(tr . - < state/ec2_ip).pem"
